//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.24 at 04:34:09 PM GMT 
//


package ecim;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ecim package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ecim
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpgradePackageContentXSDType }
     * 
     */
    public UpgradePackageContentXSDType createUpgradePackageContentXSDType() {
        return new UpgradePackageContentXSDType();
    }

    /**
     * Create an instance of {@link ManagedElementTypesXSDType }
     * 
     */
    public ManagedElementTypesXSDType createManagedElementTypesXSDType() {
        return new ManagedElementTypesXSDType();
    }

    /**
     * Create an instance of {@link UpgradePackage }
     * 
     */
    public UpgradePackage createUpgradePackage() {
        return new UpgradePackage();
    }

    /**
     * Create an instance of {@link NmsContentXSDType }
     * 
     */
    public NmsContentXSDType createNmsContentXSDType() {
        return new NmsContentXSDType();
    }

    /**
     * Create an instance of {@link ManagedElementTypeXSDType }
     * 
     */
    public ManagedElementTypeXSDType createManagedElementTypeXSDType() {
        return new ManagedElementTypeXSDType();
    }

    /**
     * Create an instance of {@link ProductDataXSDType }
     * 
     */
    public ProductDataXSDType createProductDataXSDType() {
        return new ProductDataXSDType();
    }

    /**
     * Create an instance of {@link ContentXSDType }
     * 
     */
    public ContentXSDType createContentXSDType() {
        return new ContentXSDType();
    }

    /**
     * Create an instance of {@link UpgradePackageContentXSDType.ProductData }
     * 
     */
    public UpgradePackageContentXSDType.ProductData createUpgradePackageContentXSDTypeProductData() {
        return new UpgradePackageContentXSDType.ProductData();
    }

    /**
     * Create an instance of {@link ManagedElementTypesXSDType.ManagedElementType }
     * 
     */
    public ManagedElementTypesXSDType.ManagedElementType createManagedElementTypesXSDTypeManagedElementType() {
        return new ManagedElementTypesXSDType.ManagedElementType();
    }

}
