//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.24 at 04:34:09 PM GMT 
//


package ecim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ManagedElementTypes" type="{}ManagedElementTypesXSDType"/&gt;
 *         &lt;element name="UpgradePackageContent" type="{}UpgradePackageContentXSDType"/&gt;
 *         &lt;element name="NmsContent" type="{}NmsContentXSDType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;whiteSpace value="preserve"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "managedElementTypes",
    "upgradePackageContent",
    "nmsContent"
})
@XmlRootElement(name = "UpgradePackage")
public class UpgradePackage {

    @XmlElement(name = "ManagedElementTypes", required = true)
    protected ManagedElementTypesXSDType managedElementTypes;
    @XmlElement(name = "UpgradePackageContent", required = true)
    protected UpgradePackageContentXSDType upgradePackageContent;
    @XmlElement(name = "NmsContent")
    protected NmsContentXSDType nmsContent;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the managedElementTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ManagedElementTypesXSDType }
     *     
     */
    public ManagedElementTypesXSDType getManagedElementTypes() {
        return managedElementTypes;
    }

    /**
     * Sets the value of the managedElementTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManagedElementTypesXSDType }
     *     
     */
    public void setManagedElementTypes(ManagedElementTypesXSDType value) {
        this.managedElementTypes = value;
    }

    /**
     * Gets the value of the upgradePackageContent property.
     * 
     * @return
     *     possible object is
     *     {@link UpgradePackageContentXSDType }
     *     
     */
    public UpgradePackageContentXSDType getUpgradePackageContent() {
        return upgradePackageContent;
    }

    /**
     * Sets the value of the upgradePackageContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpgradePackageContentXSDType }
     *     
     */
    public void setUpgradePackageContent(UpgradePackageContentXSDType value) {
        this.upgradePackageContent = value;
    }

    /**
     * Gets the value of the nmsContent property.
     * 
     * @return
     *     possible object is
     *     {@link NmsContentXSDType }
     *     
     */
    public NmsContentXSDType getNmsContent() {
        return nmsContent;
    }

    /**
     * Sets the value of the nmsContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link NmsContentXSDType }
     *     
     */
    public void setNmsContent(NmsContentXSDType value) {
        this.nmsContent = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
